const route = {
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  RESET_PASSWORD: 'RESET_PASSWORD',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  EMAIL_VERIFICATION: 'EMAIL_VERIFICATION',
  DASHBOARD_TAB: 'DASHBOARD_TAB',
  DASHBOARD: 'DASHBOARD',
  LOGOUT: 'LOGOUT',
  PROFILE: 'PROFILE',
  ASSET: 'ASSET',
  ASSET_TYPE: 'ASSET_TYPE',
  ADD_DEPOSIT: 'ADD_DEPOSIT',
};

export default route;
